# Generated by Django 4.0.7 on 2022-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ViewName', models.CharField(max_length=64)),
                ('Path', models.CharField(max_length=500)),
                ('Username', models.CharField(max_length=128)),
                ('Device', models.CharField(max_length=1000)),
                ('DateString', models.CharField(max_length=500)),
            ],
        ),
    ]
