# Generated by Django 4.0.7 on 2022-10-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_requestlog_datestring_requestlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
