# Generated by Django 4.0.7 on 2022-10-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_requestlog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='Method',
            field=models.CharField(default='GET', max_length=10),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='Device',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='Path',
            field=models.CharField(default='/', max_length=500),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='Username',
            field=models.CharField(default='@Anonymous', max_length=128),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='ViewName',
            field=models.CharField(default='root_app:index', max_length=64),
        ),
    ]
